#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="vtiger%20CRM%206.2.0/Core%20Product/vtigercrm6.2.0.tar.gz"
URL="http://sourceforge.net/projects/vtigercrm/files/$VERSION"

dl $URL /usr/local/src

